#!/bin/bash
#
# HLApers native-output -> common-schema standardizer.
#
# NATIVE FORMAT: one HLApers quantification TSV per sample, header
#   "locus<TAB>allele<TAB>tpm<TAB>counts"
# with allele strings prefixed "IMGT_" (e.g. "IMGT_A*01:01:01"), one row per
# candidate allele per locus (typically >=2 rows per locus; HLApers is one of
# the three tools in this project known to be able to emit >2 alleles/locus,
# see KNOWN_BUGS.md "Over-calling" entry). Worked example checked in at
# results/raw_outputs/hlapers.tsv (sample ERR188021, D1).
#
# OUTPUT SCHEMA (must match every other tool's results/standard/*.csv):
#   Sample,A,A.1,B,B.1,C,C.1,DRB1,DRB1.1,DQB1,DQB1.1
#
# -----------------------------------------------------------------------
# BUG FIX HISTORY (2026-07-22, tool-integration-engineer):
# -----------------------------------------------------------------------
# statistics-reviewer found that results/standard/hlapers_d1.csv..d6.csv had
# their DRB1 and DQB1 columns transposed: the column NAMED "DQB1" contained
# DRB1*-prefixed values and vice versa, in every row of all 6 files. See
# KNOWN_BUGS.md for full evidence and before/after accuracy numbers.
#
# ROOT CAUSE IN THIS SCRIPT (as previously checked in): the header on the old
# line 15 emitted columns in ALPHABETICAL locus order
#   ...,DQB1,DQB1.1,DRB1,DRB1.1
# (matching the internal `sort -k1,1` step, which sorts "DQB1" before "DRB1"
# alphabetically) instead of this project's established common-schema order
#   ...,DRB1,DRB1.1,DQB1,DQB1.1
# (DRB1 before DQB1, as used by every other tool's standardized CSV and by
# every datasets/*_gs.csv gold-standard file). Because the old script's data
# row was written to match that same (wrong) alphabetical order, the file
# was internally self-consistent but mislabeled relative to the schema every
# downstream scorer actually assumes when reading by column NAME -- exactly
# the transposition statistics-reviewer found.
#
# (Separately, and now also fixed below: the old script joined each locus's
# two alleles into a single comma-packed string written into one CSV field
# with a stray extra field, e.g. `...,${alleles[DQB1]},,${alleles[DRB1]},`,
# instead of writing each of the two alleles into its own dedicated column
# as the schema requires, and it did not strip the "IMGT_" reference prefix.
# These did not match the actual checked-in hlapers_d1..d6.csv byte-for-byte
# either, so this rewrite is a corrected reconstruction, not a byte-exact
# replay of whatever process originally produced those files -- it is
# written to be correct if ever re-run against fresh HLApers native output,
# per this project's "fix the conversion logic, not just the CSVs" rule.)
#
# NOTE ON THIS FIX'S SCOPE: results/standard/hlapers_d1..d6.csv were corrected
# directly (values swapped, .bak backups kept) rather than regenerated by
# running this script, because the original multi-sample raw HLApers outputs
# that produced those 6 files are not present in this repo -- only the single
# worked example results/raw_outputs/hlapers.tsv (one sample, ERR188021)
# exists, which cannot regenerate the other ~600 sample rows across d1-d6.
# See KNOWN_BUGS.md for the full disposition.
#
# Also note: results/unmapped/hlapers_unmapped.csv, results/zymo/hlapers_zymo.csv
# and results/read_length/standard/hlapers_*.csv show the SAME DRB1/DQB1
# column-name swap (and, for unmapped/zymo, also still carry the un-stripped
# "IMGT_" prefix) but are OUT OF SCOPE for this fix (task was scoped to
# results/standard/hlapers_d*.csv only) -- flagged in KNOWN_BUGS.md as
# residual/follow-up work.
# -----------------------------------------------------------------------

set -euo pipefail

# Output file name (override with: OUTPUT=myfile.csv ./hlapers_standardize.sh)
output="${OUTPUT:-hlapers_standardized.csv}"

if [ -e "${output}" ]; then
  rm "${output}"
  echo "Deleted existing ${output}"
else
  echo "${output} does not exist, creating new file."
fi

# Header: common-schema column order (DRB1 before DQB1 -- this is the fix)
echo "Sample,A,A.1,B,B.1,C,C.1,DRB1,DRB1.1,DQB1,DQB1.1" > "${output}"

# Loop through all per-sample TSV files in the current directory
for input_file in *.tsv; do
    # Extract the sample name from the file name.
    # Convention preserved from the original script: "<prefix>_<SAMPLE>.tsv".
    # Falls back to the filename stem if there is no underscore.
    if [[ "${input_file}" == *_* ]]; then
        name=$(echo "${input_file}" | awk -F'_' '{print $2}' | sed 's/\.tsv$//')
    else
        name=$(basename "${input_file}" .tsv)
    fi

    # Filter to the 5 loci we standardize, sort by locus then tpm descending,
    # keep only the top 2 rows per locus (HLApers can emit >2 candidate
    # alleles/locus -- see header comment above), strip the "IMGT_" reference
    # prefix, and normalize ambiguity separators ("-" -> "/", matching the
    # rest of this project's convention for multi-allele ambiguity strings).
    selected_alleles=$(awk -F'\t' '$1=="A" || $1=="B" || $1=="C" || $1=="DRB1" || $1=="DQB1"' "${input_file}" |
        sort -t$'\t' -k1,1 -k3,3nr |
        awk -F'\t' '{
            if ($1 != prev) { count = 0; prev = $1 }
            if (count < 2) { print; count++ }
        }' |
        sed -e 's/IMGT_//g' -e 's/-/\//g')

    # Reset per-locus allele slots for this sample
    A1=""; A2=""; B1=""; B2=""; C1=""; C2=""; DRB1_1=""; DRB1_2=""; DQB1_1=""; DQB1_2=""

    while IFS=$'\t' read -r locus allele _rest; do
        [ -z "${locus}" ] && continue
        case "${locus}" in
            A)    if [ -z "${A1}" ]; then A1="${allele}"; else A2="${allele}"; fi ;;
            B)    if [ -z "${B1}" ]; then B1="${allele}"; else B2="${allele}"; fi ;;
            C)    if [ -z "${C1}" ]; then C1="${allele}"; else C2="${allele}"; fi ;;
            DRB1) if [ -z "${DRB1_1}" ]; then DRB1_1="${allele}"; else DRB1_2="${allele}"; fi ;;
            DQB1) if [ -z "${DQB1_1}" ]; then DQB1_1="${allele}"; else DQB1_2="${allele}"; fi ;;
        esac
    done <<< "${selected_alleles}"

    # Write one row per sample -- each allele in its own column, DRB1 before
    # DQB1, matching the header exactly (no packed/comma-joined fields, no
    # stray extra fields).
    echo "${name},${A1},${A2},${B1},${B2},${C1},${C2},${DRB1_1},${DRB1_2},${DQB1_1},${DQB1_2}" >> "${output}"

    echo "Processed ${input_file}"
done

echo "All files have been combined and processed into ${output}."
